name: pre-commit

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - id: setup-python
      uses: actions/setup-python@v1
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
    - uses: pre-commit/action@v1.1.0
